### ISSUE TITLE
lapps and lif discriminators

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/org.lappsgrid.discriminator.dsl#5]
These are two separate discriminators but they have the same URI  http://vocab.lappsgrid.org/ns/media/jsonld#lif which looks funky. 

It also involves some weirdness in [discriminators.config line 143](https://github.com/lappsgrid-incubator/org.lappsgrid.discriminator.dsl/blob/master/src/main/resources/discriminators.config#L143).

Maybe get rid of one of them.

**Comment by ksuderman** [comment]
Since this is a breaking change it should really be timed with the next major release (3.0.0) of the [org.lappsgrid.discriminator](https://github.com/lapps/org.lappsgrid.discriminator) module. The DSL generates Java code so we will need to identify any other code that uses `Uri.LAPPS`.

In the meantime I will investigate marking the relevant bits of generated Java classes as `@Deprecated` so Java will warn when they are being used.

**Comment by marcverhagen** [comment]
I think this was solved in https://github.com/lapps/vocabulary-pages and can probably be closed here..

**Comment by ksuderman** [comment]
Agreed.
